name: Compilar Livro PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Compilar LaTeX (Motor PDFLaTeX)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/livro.tex
          # Forçamos o uso de pdflatex que lida melhor com PNGs
          compiler: pdflatex
          args: "-interaction=nonstopmode -file-line-error"

      - name: Upload PDF Final
        uses: actions/upload-artifact@v4
        with:
          name: Engenharia-de-Prompts-PDF
          path: src/livro.pdf