name: Compilar Livro PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Compilar LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: livro.tex
          working_directory: src
          compiler: pdflatex
          # O segredo está aqui: o latexmk garante as múltiplas passagens
          args: "-pdf -interaction=nonstopmode -file-line-error"

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Engenharia-de-Prompts-PDF
          path: src/livro.pdf