name: Compilar Livro PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Dependências LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-lang-portuguese

      - name: Compilar LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/livro.tex
          args: "-pdf -interaction=nonstopmode -halt-on-error"

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Engenharia-de-Prompts-PDF
          path: src/livro.pdf